=================================================

Milestone 3

Nama  : Christian Ambarita

Batch : CODA-014-RMT

=================================================

In [2]:
import great_expectations as gx

In [3]:
import pandas as pd

#### Import Data CSV

In [4]:
data_m3= pd.read_csv(r"C:\Users\62822\Downloads\Data_M3_1\AI_Workflow_Optimization_Dataset_2500_Rows_v1.csv")

In [5]:
data_m3

,Workflow_ID,Process_Name,Task_ID,Task_Type,Priority_Level,Department,Assigned_Employee_ID,Task_Start_Time,Task_End_Time,Estimated_Time_Minutes,Actual_Time_Minutes,Delay_Flag,Approval_Level,Employee_Workload,Cost_Per_Task
0,WF_1,Customer Complaint,TASK_1,Review,Low,Customer Service,EMP_128,2024-01-25 04:47:00,2024-01-25 08:33:00,208,226,1,Level 1,1,155.17
1,WF_2,HR Onboarding,TASK_2,Approval,Low,HR,EMP_35,2024-05-24 02:57:00,2024-05-24 06:19:00,194,202,1,Level 2,5,231.54
2,WF_3,Invoice Approval,TASK_3,Review,High,Finance,EMP_88,2024-03-22 03:34:00,2024-03-22 08:51:00,214,317,1,Level 1,8,280.95
3,WF_4,Customer Complaint,TASK_4,Review,Medium,Operations,EMP_133,2024-06-10 10:37:00,2024-06-10 13:36:00,176,179,1,Level 3,1,413.74
4,WF_5,Customer Complaint,TASK_5,Escalation,Medium,Finance,EMP_80,2024-07-02 11:38:00,2024-07-02 15:36:00,197,238,1,Level 3,3,152.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,WF_2496,HR Onboarding,TASK_2496,Approval,Critical,Customer Service,EMP_14,2024-01-29 09:48:00,2024-01-29 10:58:00,33,70,1,Level 3,8,143.87
2496,WF_2497,HR Onboarding,TASK_2497,Review,Critical,IT,EMP_27,2024-04-30 05:47:00,2024-04-30 10:00:00,227,253,1,Level 2,10,335.42
2497,WF_2498,IT Support Ticket,TASK_2498,Approval,High,IT,EMP_123,2024-03-25 10:02:00,2024-03-25 14:26:00,167,264,1,Level 2,4,451.91
2498,WF_2499,Customer Complaint,TASK_2499,Validation,High,IT,EMP_12,2024-07-12 09:03:00,2024-07-12 12:57:00,169,234,1,Level 1,7,334.07
2499,WF_2500,IT Support Ticket,TASK_2500,Data Entry,Medium,Finance,EMP_63,2024-02-02 01:40:00,2024-02-02 03:16:00,89,96,1,Level 3,7,274.87

#### EDA

In [6]:
# melihat apakah tipe data sudah sesuai
data_m3.info()
# dapat dilihat bahwa tipe data sudah sesuai dengan yang kolomnya masing2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Workflow_ID             2500 non-null   object
 1   Process_Name            2500 non-null   object
 2   Task_ID                 2500 non-null   object
 3   Task_Type               2500 non-null   object
 4   Priority_Level          2500 non-null   object
 5   Department              2500 non-null   object
 6   Assigned_Employee_ID    2500 non-null   object
 7   Task_Start_Time         2500 non-null   object
 8   Task_End_Time           2500 non-null   object
 9   Estimated_Time_Minutes  2500 non-null   int64
 10  Actual_Time_Minutes     2500 non-null   int64
 11  Delay_Flag              2500 non-null   int64
 12  Approval_Level          2500 non-null   object
 13  Employee_Workload       2500 non-null   int64
 14  Cost_Per_Task           2500 non-null   float64
dtypes: float64(1), int64(4), object(10)
memory usage: 293.1+ KB

In [7]:
#Melihat apakah ada yang null di data atau tidak
data_m3.isnull().sum()
#Dibuat sederhana seperti ini karena takutnya ada yang dianggap duplikat padahal cuma karena sama dalam suatu atau bebeberapa kolom saja

Workflow_ID               0
Process_Name              0
Task_ID                   0
Task_Type                 0
Priority_Level            0
Department                0
Assigned_Employee_ID      0
Task_Start_Time           0
Task_End_Time             0
Estimated_Time_Minutes    0
Actual_Time_Minutes       0
Delay_Flag                0
Approval_Level            0
Employee_Workload         0
Cost_Per_Task             0
dtype: int64

In [8]:
# Melihat apakah ada yang missing values dari data atau tidak
missing_df = pd.DataFrame({
    'Missing Count': data_m3.isnull().sum(),
    'Missing Percentage': (data_m3.isnull().mean() * 100).round(2)
})

missing_df = missing_df[missing_df['Missing Count'] > 0]

print('Missing Values Analysis:')
print('=' * 50)
print(missing_df)
print(f'\nTotal Kolom dengan Missing Values: {len(missing_df)}')

#maka karena tidak ada yang missing values, maka tidak perlu dilakukan penanganan lebih lanjut

Missing Values Analysis:
==================================================
Empty DataFrame
Columns: [Missing Count, Missing Percentage]
Index: []

Total Kolom dengan Missing Values: 0

##### Maka, Tidak perlu ada penanganan transformasi

#### Data Validation

In [9]:
# Create a data context

from great_expectations.data_context import FileDataContext

context = FileDataContext.create(project_root_dir='./')

In [10]:
datasource_name = "csv-data-Terbaru_M3_Fin"
datasource = context.sources.add_pandas(datasource_name)

asset_name = "Workflow-Terbaru"

asset = datasource.add_dataframe_asset(name=asset_name)

batch_request = asset.build_batch_request(
    dataframe=data_m3
)

In [11]:
suite_name = "expectation_data_m3"
context.add_or_update_expectation_suite(expectation_suite_name=suite_name)
validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name=suite_name
)
validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,Workflow_ID,Process_Name,Task_ID,Task_Type,Priority_Level,Department,Assigned_Employee_ID,Task_Start_Time,Task_End_Time,Estimated_Time_Minutes,Actual_Time_Minutes,Delay_Flag,Approval_Level,Employee_Workload,Cost_Per_Task
0,WF_1,Customer Complaint,TASK_1,Review,Low,Customer Service,EMP_128,2024-01-25 04:47:00,2024-01-25 08:33:00,208,226,1,Level 1,1,155.17
1,WF_2,HR Onboarding,TASK_2,Approval,Low,HR,EMP_35,2024-05-24 02:57:00,2024-05-24 06:19:00,194,202,1,Level 2,5,231.54
2,WF_3,Invoice Approval,TASK_3,Review,High,Finance,EMP_88,2024-03-22 03:34:00,2024-03-22 08:51:00,214,317,1,Level 1,8,280.95
3,WF_4,Customer Complaint,TASK_4,Review,Medium,Operations,EMP_133,2024-06-10 10:37:00,2024-06-10 13:36:00,176,179,1,Level 3,1,413.74
4,WF_5,Customer Complaint,TASK_5,Escalation,Medium,Finance,EMP_80,2024-07-02 11:38:00,2024-07-02 15:36:00,197,238,1,Level 3,3,152.30

#### Expectation

In [12]:
#Ekspektasi 1:  untuk memastikan bahwa nilai Task_ID harus unik
validator.expect_column_values_to_be_unique("Task_ID")

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [13]:
#Ekspektasi 1:  untuk memastikan bahwa nilai Workflow_ID harus unik
validator.expect_column_values_to_be_unique("Workflow_ID")

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [14]:
#Ekspektasi 2: Kolom Delay_Flag hanya boleh berisi nilai 0(Tidak Delay) atau 1(Delay) pekerjaannya
validator.expect_column_values_to_be_in_set("Delay_Flag", [0,1])

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [15]:
#Ekspektasi 3: Kolom Priority_Level hanya boleh berisi nilai Low, Medium, High, atau Critical
validator.expect_column_values_to_be_in_set("Priority_Level", ["Low","Medium","High","Critical"])

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [16]:
#Ekspektasi 4: Kolom Approval_Level hanya boleh berisi nilai Level 1, Level 2, atau Level 3
validator.expect_column_values_to_be_in_set("Approval_Level", ["Level 1","Level 2","Level 3"])

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [17]:
#Ekspektasi 5: Kolom Estimated_Time_Minutes dan Actual_Time_Minutes hanya boleh berisi nilai antara 0 dan 1440 (24 jam)
validator.expect_column_values_to_be_between("Estimated_Time_Minutes", min_value=0, max_value=1440)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [18]:
validator.expect_column_values_to_be_between("Actual_Time_Minutes", min_value=0)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [19]:
#Ekspektasi 6: Kolom Task_End_Time harus lebih besar dari Task_Start_Time
validator.expect_column_pair_values_A_to_be_greater_than_B(column_A="Task_End_Time",column_B="Task_Start_Time")

Calculating Metrics:   0%|          | 0/7 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [20]:
#Ekspektasi 7: Kolom Employee_Workload harus berisi nilai yang lebih besar dari 0 karena tidak mungkin pekerjaannya tidak ada atau 0, maka harus lebih besar dari 0
validator.expect_column_values_to_be_between("Employee_Workload", min_value=1)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [21]:
#Ekspektasi 8: Kolom Task_ID tidak boleh bernilai null
validator.expect_column_values_to_not_be_null("Task_ID")

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [22]:
#Ekspektasi 9: kolom Workflow_ID harus bernilai WF_(Angka)
validator.expect_column_values_to_match_regex("Workflow_ID", r"^WF_\d+$")

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [23]:
#Ekspektasi 10: kolom Task_ID harus bernilai TASK_(Angka)
validator.expect_column_values_to_match_regex("Task_ID",r"^TASK_\d+$")

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 2500,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [24]:
validator.get_expectation_suite().expectations

[{"expectation_type": "expect_column_values_to_be_unique", "kwargs": {"column": "Task_ID"}, "meta": {}},
 {"expectation_type": "expect_column_values_to_be_unique", "kwargs": {"column": "Workflow_ID"}, "meta": {}},
 {"expectation_type": "expect_column_values_to_be_in_set", "kwargs": {"column": "Delay_Flag", "value_set": [0, 1]}, "meta": {}},
 {"expectation_type": "expect_column_values_to_be_in_set", "kwargs": {"column": "Priority_Level", "value_set": ["Low", "Medium", "High", "Critical"]}, "meta": {}},
 {"expectation_type": "expect_column_values_to_be_in_set", "kwargs": {"column": "Approval_Level", "value_set": ["Level 1", "Level 2", "Level 3"]}, "meta": {}},
 {"expectation_type": "expect_column_values_to_be_between", "kwargs": {"min_value": 0, "max_value": 1440, "column": "Estimated_Time_Minutes"}, "meta": {}},
 {"expectation_type": "expect_column_values_to_be_between", "kwargs": {"min_value": 0, "column": "Actual_Time_Minutes"}, "meta": {}},
 {"expectation_type": "expect_column_pair_values_a_to_be_greater_than_b", "kwargs": {"column_A": "Task_End_Time", "column_B": "Task_Start_Time"}, "meta": {}},
 {"expectation_type": "expect_column_values_to_be_between", "kwargs": {"min_value": 1, "column": "Employee_Workload"}, "meta": {}},
 {"expectation_type": "expect_column_values_to_not_be_null", "kwargs": {"column": "Task_ID"}, "meta": {}},
 {"expectation_type": "expect_column_values_to_match_regex", "kwargs": {"column": "Workflow_ID", "regex": "^WF_\\d+$"}, "meta": {}},
 {"expectation_type": "expect_column_values_to_match_regex", "kwargs": {"column": "Task_ID", "regex": "^TASK_\\d+$"}, "meta": {}}]

In [25]:
validator.save_expectation_suite()

In [ ]:
#menambahkan checkpoint untuk menjalankan validasi
checkpoint = context.add_or_update_checkpoint(
    name="cp_data_m3_final",
    validations=[{ "batch_request": batch_request,"expectation_suite_name": suite_name,}],
)

In [27]:
checkpoint.run()

Calculating Metrics:   0%|          | 0/78 [00:00<?, ?it/s]

{
  "run_id": {
    "run_name": null,
    "run_time": "2026-02-23T14:38:54.785024+07:00"
  },
  "run_results": {
    "ValidationResultIdentifier::expectation_data_m3/__none__/20260223T073854.785024Z/csv-data-Terbaru_M3_Fin-Workflow-Terbaru": {
      "validation_result": {
        "success": true,
        "results": [
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_unique",
              "kwargs": {
                "column": "Task_ID",
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_not_be_null",
              "kwargs": {
                "column": "Task_ID",
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_match_regex",
              "kwargs": {
                "column": "Task_ID",
                "regex": "^TASK_\\d+$",
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_unique",
              "kwargs": {
                "column": "Workflow_ID",
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_match_regex",
              "kwargs": {
                "column": "Workflow_ID",
                "regex": "^WF_\\d+$",
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_in_set",
              "kwargs": {
                "column": "Delay_Flag",
                "value_set": [
                  0,
                  1
                ],
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_in_set",
              "kwargs": {
                "column": "Priority_Level",
                "value_set": [
                  "Low",
                  "Medium",
                  "High",
                  "Critical"
                ],
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_in_set",
              "kwargs": {
                "column": "Approval_Level",
                "value_set": [
                  "Level 1",
                  "Level 2",
                  "Level 3"
                ],
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_between",
              "kwargs": {
                "column": "Estimated_Time_Minutes",
                "max_value": 1440,
                "min_value": 0,
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_between",
              "kwargs": {
                "column": "Actual_Time_Minutes",
                "min_value": 0,
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_pair_values_a_to_be_greater_than_b",
              "kwargs": {
                "column_A": "Task_End_Time",
                "column_B": "Task_Start_Time",
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_column_values_to_be_between",
              "kwargs": {
                "column": "Employee_Workload",
                "min_value": 1,
                "batch_id": "csv-data-Terbaru_M3_Fin-Workflow-Terbaru"
              },
              "meta": {}
            },
            "result": {
              "element_count": 2500,
              "unexpected_count": 0,
              "unexpected_percent": 0.0,
              "partial_unexpected_list": [],
              "missing_count": 0,
              "missing_percent": 0.0,
              "unexpected_percent_total": 0.0,
              "unexpected_percent_nonmissing": 0.0,
              "partial_unexpected_counts": [],
              "partial_unexpected_index_list": []
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          }
        ],
        "evaluation_parameters": {},
        "statistics": {
          "evaluated_expectations": 12,
          "successful_expectations": 12,
          "unsuccessful_expectations": 0,
          "success_percent": 100.0
        },
        "meta": {
          "great_expectations_version": "0.18.19",
          "expectation_suite_name": "expectation_data_m3",
          "run_id": {
            "run_name": null,
            "run_time": "2026-02-23T14:38:54.785024+07:00"
          },
          "batch_spec": {
            "batch_data": "PandasDataFrame"
          },
          "batch_markers": {
            "ge_load_time": "20260223T073854.802733Z",
            "pandas_data_fingerprint": "5f1d033a4f85b524b0cbc113cec6f200"
          },
          "active_batch_definition": {
            "datasource_name": "csv-data-Terbaru_M3_Fin",
            "data_connector_name": "fluent",
            "data_asset_name": "Workflow-Terbaru",
            "batch_identifiers": {}
          },
          "validation_time": "20260223T073854.814294Z",
          "checkpoint_name": "cp_data_m3_final",
          "validation_id": null,
          "checkpoint_id": null
        }
      },
      "actions_results": {
        "store_validation_result": {
          "class": "StoreValidationResultAction"
        },
        "store_evaluation_params": {
          "class": "StoreEvaluationParametersAction"
        },
        "update_data_docs": {
          "local_site": "file://c:\\Users\\62822\\Downloads\\gx\\uncommitted/data_docs/local_site/validations%5Cexpectation_data_m3%5C__none__%5C20260223T073854.785024Z%5Ccsv-data-Terbaru_M3_Fin-Workflow-Terbaru.html",
          "class": "UpdateDataDocsAction"
        }
      }
    }
  },
  "checkpoint_config": {
    "action_list": [
      {
        "name": "store_validation_result",
        "action": {
          "class_name": "StoreValidationResultAction"
        }
      },
      {
        "name": "store_evaluation_params",
        "action": {
          "class_name": "StoreEvaluationParametersAction"
        }
      },
      {
        "name": "update_data_docs",
        "action": {
          "class_name": "UpdateDataDocsAction"
        }
      }
    ],
    "batch_request": {},
    "default_validation_id": null,
    "expectation_suite_name": null,
    "run_name_template": null,
    "runtime_configuration": {},
    "config_version": 1.0,
    "site_names": null,
    "validations": [
      {
        "batch_request": {
          "datasource_name": "csv-data-Terbaru_M3_Fin",
          "data_asset_name": "Workflow-Terbaru",
          "options": {},
          "batch_slice": null
        },
        "expectation_suite_ge_cloud_id": null,
        "name": null,
        "id": null,
        "expectation_suite_name": "expectation_data_m3"
      }
    ],
    "notify_on": null,
    "expectation_suite_ge_cloud_id": null,
    "notify_with": null,
    "ge_cloud_id": null,
    "name": "cp_data_m3_final",
    "class_name": "Checkpoint",
    "profilers": [],
    "slack_webhook": null,
    "module_name": "great_expectations.checkpoint",
    "template_name": null,
    "evaluation_parameters": {}
  },
  "success": true
}

In [ ]:
#membuka data docs untuk melihat hasil validasi great expectations
context.build_data_docs()
context.open_data_docs()